apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: postgres
  name: postgres
spec:
  containers:
  - image: postgres
    name: postgres
    env:
    - name: POSTGRES_DB
      value: "gogs"
    - name: POSTGRES_USER
      value: "gogs"
    - name: POSTGRES_PASSWORD
      value: "gogs"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gogs
  name: gogs
spec:
  containers:
  - image: gogs/gogs
    name: gogs
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
